version: '3.8'


services:
  oop-app-container:
    # image: php:8.3-apache
    build: 
      context: .
      dockerfile: Dockerfile
    restart: no
    volumes:
      - ./website:/var/www/html/

    ports:
      - 8088:80